/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flarejaven_example_jnithread_NdkJniUtils */

#ifndef _Included_com_flarejaven_example_jnithread_NdkJniUtils
#define _Included_com_flarejaven_example_jnithread_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flarejaven_example_jnithread_NdkJniUtils
 * Method:    startThread
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_flarejaven_example_jnithread_NdkJniUtils_startThread
  (JNIEnv *, jobject);

/*
 * Class:     com_flarejaven_example_jnithread_NdkJniUtils
 * Method:    endThread
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_flarejaven_example_jnithread_NdkJniUtils_endThread
  (JNIEnv *, jobject);

/*
 * Class:     com_flarejaven_example_jnithread_NdkJniUtils
 * Method:    setJNIEnv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_flarejaven_example_jnithread_NdkJniUtils_setJNIEnv
  (JNIEnv *, jobject);

/*
 * Class:     com_flarejaven_example_jnithread_NdkJniUtils
 * Method:    configStickerNames
 * Signature: ([Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_flarejaven_example_jnithread_NdkJniUtils_configStickerNames
  (JNIEnv *, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
